apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
        - name: rooms
          image: niimu/mmrooms
          env:
            - name: MONGO_URI
              value: 'mongodb://rooms-mongo-srv:27017/rooms'
            - name: JWT_KEY
              value: 'asdf'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: megamind
---
apiVersion: v1
kind: Service
metadata:
  name: rooms-srv
spec:
  selector:
    app: rooms
  ports:
    - name: rooms
      protocol: TCP
      port: 3000
      targetPort: 3000
